title: Zhikai Huang
url: "https://huangzk.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/icecrystals"
footer_text: "My Github Link"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "mailto:hzhikai97@gmail.com"
 - name: "Chinese Blog"
   link: "https://dayday.plus"
